language: ruby
rvm:
- 2.2
- 2.1
- 2.0
env:
  global:
    secure: sI0+Gt/spIU2jh/RHCzQva9C4TW8HvL8pXAKpi1xAfcDeLL1M2yuSQWV/R/akGZMfXg37zXHCN0IGEmV6OkGu2riiF03CVSO8UZrrwXVEKnwGFbzobVe5YZt2gHSVN43m0b27g3hYXNBGEc1vy1U49riWHgMyVa0+ZmfzRxo0Gbx0RQlpbpXaHeZzwjy+Heul7BA7iLNowHatWeyVoB1J3+R1bazuYMS6jJy5IK9WHzvTo2btvb4+Vum4xJMyhUlHQUBIqMu3lS1q4rcnO2QQbj2eiJPFm2WRb2entqQ8MZh69A1gViWVbPQoW1cHudmNYHNSPoyPOPQWuhM6RcGZ9JUQRL/ibvrS5xLnHwSly3RWPowaUTciY4aPaawUBJrhbj3ayGiDH+2spQMEoFYTnY/uUfzdQS9jdc5evPJThRk8Zrn+W/bbRtscd7jejZG9QRxHngDxJCN/rIt994zyj+iakGnNKs/wKpBvdoocaxBKbSXKvBy3QJMY+isscWrQ5uCzHjookUbHxqPYdvSKpYXf5LGMfIyJRG3IQRLC4dVythlAgk1Hq5K4M6e5wk6ALaHwesXlTPH9pIkL0wQm8q4N965BS6MQgl9Bz8dNuKA+mZW01C21osvAPN+IcMhuSTQMsLptY/2smOOfs5MRm0iRUSiFYzOPZ4TjQdKS1c=
